export type Album = {
    artist: string;
    albumTitle: string;
    videoLink: string;
    cover: string;
    startTime: number;
};
export const albums: Album[] = [
    {
        artist: "Meaningful Stone",
        albumTitle: "Angel Interview",
        videoLink: "https://www.youtube.com/watch?v=059MGiB2Kr4",
        cover: "/covers/1-MeaningfulStone.webp",
        startTime: 171,
    },
    {
        artist: "Clairo",
        albumTitle: "Charm",
        videoLink: "https://www.youtube.com/watch?v=iUxlnNnAoTc",
        cover: "/covers/2-Clairo.webp",
        startTime: 137,
    },
    {
        artist: "Magdalena Bay",
        albumTitle: "Imaginal Disk",
        videoLink: "https://www.youtube.com/watch?v=bd1i6CYVE6c",
        cover: "/covers/3-MagdalenaBay.webp",
        startTime: 169,
    },
    {
        artist: "Billie Eilish",
        albumTitle: "Hit Me Hard and Soft",
        videoLink: "https://www.youtube.com/watch?v=V9PVRfjEBTI",
        cover: "/covers/4-BillieEilish.webp",
        startTime: 143,
    },
    {
        artist: "Charli XCX",
        albumTitle: "Brat",
        videoLink: "https://www.youtube.com/watch?v=WJW-VvmRKsE",
        cover: "/covers/5-CharliXCX.webp",
        startTime: 199,
    },
    {
        artist: "Scandal",
        albumTitle: "Luminous",
        videoLink: "https://www.youtube.com/watch?v=4ye9nC4Xy3M",
        cover: "/covers/6-Scandal.webp",
        startTime: 162,
    },
    {
        artist: "Logic",
        albumTitle: "Ultra 85",
        videoLink: "https://www.youtube.com/watch?v=8U08jK8IVjc",
        cover: "/covers/7-Logic.webp",
        startTime: 50,
    },
    {
        artist: "Godspeed You! Black Emperor",
        albumTitle: "No Title as of 13 February 2024 28,340 Dead",
        videoLink: "https://www.youtube.com/watch?v=Q8-55QejRck",
        cover: "/covers/8-GodspeedYouBlackEmperor.webp",
        startTime: 705,
    },
    {
        artist: "Remi Wolf",
        albumTitle: "Big Ideas",
        videoLink: "https://www.youtube.com/watch?v=4A7LIv_2Ips",
        cover: "/covers/9-RemiWolf.webp",
        startTime: 103,
    },
    {
        artist: "Quadeca",
        albumTitle: "Scrapyard",
        videoLink: "https://www.youtube.com/watch?v=QxU1G44iOpc",
        cover: "/covers/10-Quadeca.webp",
        startTime: 97,
    },
    {
        artist: "Aurora",
        albumTitle: "What Happened to the Heart?",
        videoLink: "https://www.youtube.com/watch?v=KKuPq1Opc60",
        cover: "/covers/11-Aurora.webp",
        startTime: 195,
    },
    {
        artist: "Poppy",
        albumTitle: "Negative Spaces",
        videoLink: "https://www.youtube.com/watch?v=OqVNYcaS-3E",
        cover: "/covers/12-Poppy.webp",
        startTime: 51,
    },
    {
        artist: "Willow",
        albumTitle: "Empathogen",
        videoLink: "https://www.youtube.com/watch?v=wQtVSNmYCNg",
        cover: "/covers/13-Willow.webp",
        startTime: 98,
    },
    {
        artist: "The Last Dinner Party",
        albumTitle: "Prelude to Ecstasy",
        videoLink: "https://www.youtube.com/watch?v=wqcYU_eoihU",
        cover: "/covers/14-TheLastDinnerParty.webp",
        startTime: 171,
    },
    {
        artist: "Laura Marling",
        albumTitle: "Patterns in Repeat",
        videoLink: "https://www.youtube.com/watch?v=8QH0bONb7RQ",
        cover: "/covers/15-LauraMarling.webp",
        startTime: 29,
    },
    {
        artist: "Chelsea Wolfe",
        albumTitle: "She Reaches Out to She Reaches Out to She",
        videoLink: "https://www.youtube.com/watch?v=a4KJRuADHQE",
        cover: "/covers/16-ChelseaWolfe.webp",
        startTime: 119,
    },
    {
        artist: "Tyler, The Creator",
        albumTitle: "Chromakopia",
        videoLink: "https://www.youtube.com/watch?v=Qer3lwd5hyA",
        cover: "/covers/17-TylerTheCreator.webp",
        startTime: 62,
    },
    {
        artist: "Joanna Wang",
        albumTitle: "Hotel la Rut",
        videoLink: "https://www.youtube.com/watch?v=8MXInlatmOU",
        cover: "/covers/18-JoannaWang.webp",
        startTime: 124,
    },
    {
        artist: "Akrilla",
        albumTitle: "epistolares",
        videoLink: "https://www.youtube.com/watch?v=2e2oKjgh1YQ",
        cover: "/covers/19-Akrilla.webp",
        startTime: 167,
    },
    {
        artist: "Porter Robinson",
        albumTitle: "SMILE! :D",
        videoLink: "https://www.youtube.com/watch?v=CzJbz9qSsd0",
        cover: "/covers/20-PorterRobinson.webp",
        startTime: 122,
    },
    {
        artist: "Kendrick Lamar",
        albumTitle: "GNX",
        videoLink: "https://www.youtube.com/watch?v=fuV4yQWdn_4",
        cover: "/covers/21-KendrickLamar.webp",
        startTime: 4,
    },
    {
        artist: "Geordie Greep",
        albumTitle: "The New Sound",
        videoLink: "https://www.youtube.com/watch?v=A4EU_0vFzuU",
        cover: "/covers/22-GeordieGreep.webp",
        startTime: 65,
    },
    {
        artist: "English Teacher",
        albumTitle: "This Could Be Texas",
        videoLink: "https://www.youtube.com/watch?v=YNkbgumvYyA",
        cover: "/covers/23-EnglishTeacher.webp",
        startTime: 45,
    },
    {
        artist: "Sabrina Carpenter",
        albumTitle: "Short n' Sweet",
        videoLink: "https://www.youtube.com/watch?v=cF1Na4AIecM",
        cover: "/covers/24-SabrinaCarpenter.webp",
        startTime: 175,
    },
    {
        artist: "Mach-Hommy",
        albumTitle: "`#`RICHAXXHAITIAN",
        videoLink: "https://www.youtube.com/watch?v=_A6ApDZkdzc",
        cover: "/covers/25-MachHommy.webp",
        startTime: 30,
    },
];
